# Generated by Django 4.1 on 2022-09-28 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('begin_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Schedule Profile',
                'verbose_name_plural': 'Schedule Profiles',
            },
        ),
        migrations.CreateModel(
            name='ScheduleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon_time', models.CharField(max_length=8)),
                ('tue_time', models.CharField(max_length=8)),
                ('wed_time', models.CharField(max_length=8)),
                ('thr_time', models.CharField(max_length=8)),
                ('fri_time', models.CharField(max_length=8)),
                ('sat_time', models.CharField(max_length=8)),
                ('sun_time', models.CharField(max_length=8)),
                ('mon_duty', models.CharField(blank=True, max_length=100, null=True)),
                ('tue_duty', models.CharField(blank=True, max_length=100, null=True)),
                ('wed_duty', models.CharField(blank=True, max_length=100, null=True)),
                ('thr_duty', models.CharField(blank=True, max_length=100, null=True)),
                ('fri_duty', models.CharField(blank=True, max_length=100, null=True)),
                ('sat_duty', models.CharField(blank=True, max_length=100, null=True)),
                ('sun_duty', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.employee')),
                ('schedule_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.scheduleprofile')),
            ],
            options={
                'verbose_name': 'Schedule Detail',
                'verbose_name_plural': 'Schedule Details',
            },
        ),
        migrations.CreateModel(
            name='CurrentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.scheduleprofile')),
            ],
            options={
                'verbose_name': 'Current Schedule',
                'verbose_name_plural': 'Current Schedules',
            },
        ),
    ]
