# Generated by Django 4.1 on 2022-09-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_scheduleprofile_scheduledetail_currentschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledetail',
            name='fri_time',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledetail',
            name='mon_time',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledetail',
            name='sat_time',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledetail',
            name='sun_time',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledetail',
            name='thr_time',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledetail',
            name='tue_time',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledetail',
            name='wed_time',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
