# Generated by Django 4.1 on 2022-09-29 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_scheduledetail_fri_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledetail',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.employee'),
        ),
    ]
