# Generated by Django 4.1 on 2022-09-29 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_scheduledetail_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledetail',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.employee'),
        ),
    ]
