# Generated by Django 4.1 on 2023-02-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_scheduledetail_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledetail',
            old_name='mon_duty',
            new_name='day_1_duty',
        ),
        migrations.RenameField(
            model_name='scheduledetail',
            old_name='mon_time',
            new_name='day_1_time',
        ),
        migrations.RenameField(
            model_name='scheduledetail',
            old_name='tue_duty',
            new_name='day_2_duty',
        ),
        migrations.RenameField(
            model_name='scheduledetail',
            old_name='tue_time',
            new_name='day_2_time',
        ),
        migrations.RenameField(
            model_name='scheduledetail',
            old_name='wed_duty',
            new_name='day_3_duty',
        ),
        migrations.RenameField(
            model_name='scheduledetail',
            old_name='wed_time',
            new_name='day_3_time',
        ),
        migrations.RenameField(
            model_name='scheduledetail',
            old_name='thr_duty',
            new_name='day_4_duty',
        ),
        migrations.RenameField(
            model_name='scheduledetail',
            old_name='thr_time',
            new_name='day_4_time',
        ),
        migrations.RenameField(
            model_name='scheduledetail',
            old_name='fri_duty',
            new_name='day_5_duty',
        ),
        migrations.RenameField(
            model_name='scheduledetail',
            old_name='fri_time',
            new_name='day_5_time',
        ),
        migrations.RenameField(
            model_name='scheduledetail',
            old_name='sat_duty',
            new_name='day_6_duty',
        ),
        migrations.RenameField(
            model_name='scheduledetail',
            old_name='sat_time',
            new_name='day_6_time',
        ),
        migrations.RenameField(
            model_name='scheduledetail',
            old_name='sun_duty',
            new_name='day_7_duty',
        ),
        migrations.RenameField(
            model_name='scheduledetail',
            old_name='sun_time',
            new_name='day_7_time',
        ),
    ]
